# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift lint

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Lint
        run: set -o pipefail && swiftlint lint --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'
